event = {
    "event_id" : "",
    "sport" : "",
    "sport_id" : 0,
    "video_sources" : str([]),
    "socket_video_sources" : str([]),
    "audio_sources" : str([]),
    "start": int(False),
    "play": int(False),
    "stop": int(False),
    "interrupt_flag": int(False),
    "selected_video_source": 0,
    "video_frame": "",
    "creator_user_id": "",
}